 - name: SSH into the server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PASSWORD }}
        script: |
          git pull origin main
          echo "${{ secrets.SERVER_USER_PASSWORD }}" | sudo cp /src/.env /home/ubuntu/server/
          echo "${{ secrets.SERVER_USER_PASSWORD }}" | sudo supervisorctl reread
          echo "${{ secrets.SERVER_USER_PASSWORD }}" | sudo supervisorctl update
          echo "${{ secrets.SERVER_USER_PASSWORD }}" | sudo supervisorctl restart server
