name: Docker Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: SSH into the server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PASSWORD }}
        script: |
          whoami
